### PR TITLE
Modify add command

### LINKED ISSUE #69: implement add feature

### PR DESCRIPTION
**Pull request by umergta**
- change prefixes and order of processing
- change handling of duplicate task handling to check name and module
- modify tests accordingly 
- update documentation (UG and DG)

### CODE REVIEW

**Review by yhtMinceraft1010X — COMMENTED** [review]
Documentation and logic wise, LGTM

**Review by QY-H00 — COMMENTED** [review]
LGTM for test part.

**Review by AiwassPrime — COMMENTED** [review]
Test part LGTM

**Review by figo2127 — COMMENTED** [review]
LGTM overall!

**Pull request merged**
