### PR TITLE
fix time parsing and use internal java time exceptions [Not complete]

### LINKED ISSUE #147: Bug on "Time"
1. Add 29th, Feb on non-leap year, exception is not caught.
2. Add 29th, Feb on non-leap year but with time field, can add without any error message.
3. Exception will be thrown when input this kind of time "5:30".

### LINKED ISSUE #150: [PE-D] No exception thrown wrong deadline given
Try to add new task with unique name, correct params except the deadline (I set 29 feb on a non-leap year). Cannot add and no exception shown. (I have tried press enter multiple times)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: austenjs/ped#3

### LINKED ISSUE #169: [PE-D] No error shown when editing with wrong deadline format
Try to edit but nothing happen. No error is shown

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: austenjs/ped#22

### PR DESCRIPTION
**Pull request by umergta**
errors fixed: accepting time like "2021-05-05 5:10"
Use java exceptions instead of regex matching for safer handling

[edit]
- fixed leap year issue. e.g. "2021-02-29" not accepted.
- parse the HH:mm field and yyyy-MM-dd fields seperately to use ISO date time formatters as they seem to handle invalid inputs of month and time. 
- changed recur's monthly to biweekly and neatened up recur Time construction.
- remove commented out code

[todo] 
- add some tests for the new methods constructed.
- Maybe change the error messages for time..? (maybe you guys can give suggestions)

### CODE REVIEW

**Review by yhtMinceraft1010X — COMMENTED** [review]
LGTM, but I think the AddCommand still has commented out code.

**Comment by umergta** [comment]
> LGTM, but I think the AddCommand still has commented out code.

roger that. Will remove in next commit!
[resolved]

**Review by yhtMinceraft1010X — COMMENTED** [review]
LGTM, but I also recommend describing the implementation of recurrence in DG and updating the monthly to biweekly in UG

**Review by figo2127 — COMMENTED** [review]
LGTM! Did not find any big issues. Good job Umer!

**Comment by figo2127** [comment]
> LGTM, but I also recommend describing the implementation of recurrence in DG and updating the monthly to biweekly in UG

Yep, remember to add to UG.

**Pull request merged**
