### PR TITLE
Pr period

### LINKED ISSUE #97: Add time period for tasks

### PR DESCRIPTION
**Pull request by AiwassPrime**
A new field of startTime is implemented as an optional field, instead of two classes inherit from an abstract class.
"a/[TIME]" is used for startTime, which stand for "after" startTime.
startTime will be assigned to null and isDeadline will be true if that field is not present.
Can be changed to using Optional with not much effort. Reasons not doing so:

1. The yellow warning will show up, annoying.
image
2. Optional<Time> will not make life easier, still need to check isEmpty everywhere.
3. CS2103T does not have restrictions on using null.

I have changed the class "Deadline" to "Time", as now this class serves more than a deadline, it can also be a start time.
The UML graph in DG is not updated.

Pls raise any concern you have.

### CODE REVIEW

**Review by yhtMinceraft1010X — COMMENTED** [review]
Current changes LGTM

**Review by yhtMinceraft1010X — COMMENTED** [review]
LGTM

**Review by QY-H00 — COMMENTED** [review]
LGTM.

**Comment by umergta** [comment]
LGTM

**Review by figo2127 — COMMENTED** [review]
lgtm!

**Pull request merged**
